### ISSUE TITLE
2fa blocks theming and custom css

### ISSUE THREAD

**Issue by dodedodo** [nextcloud/theming_customcss#27]
Hi! 

When a 2fa login is initiated, the `/apps/theming_customcss/styles?v=xxx` cannot be loaded by the browser because it is redirected to `/login/selectchalenge....` because of the 2fa flow. This makes theming of the 2fa login process impossible.

This issue also applies to other stuff like the favicon, logo, plugin scripts, merged-template-prepend.js and various stylesheets (although I don't know if this introduces bugs). You can see a list of these files by opening your browser's development tools when asked for the 2fa confirmation, and filtering the http 303 requests in the network tab.

Tested on nextcloud v23.0.0 with 'Two-Factor Authentication via Nextcloud notification'. 

I'm not sure, but this might be addressed by [nextcloud/server#29752](https://github.com/nextcloud/server/pull/29752)? Does this app need to specify its public routes?

**Comment by juliushaertl** [comment]
Should add `@NoTwoFactorRequired` to the controller.
