### ISSUE TITLE
How can I recover to original status if my customize css code is defective?

### ISSUE THREAD

**Issue by WXpiero** [nextcloud/theming_customcss#30]
Now my code makes the NC page unaccessible, I don't know how to recover back to the status when it still working,I can only disable the customize css app from the occ command line, maybe there could be two buttons, a preview button makes the effect only apply for a few seconds ,if the code is defective it can change back to the normal state automaticlly. and another true apply button that really makes the code apply permanently.

**Comment by juliushaertl** [comment]
You can reset the code through occ commands described in here:

https://github.com/juliushaertl/theming_customcss/issues/20#issuecomment-793090221

Leaving this open for the idea of a preview mode.

**Comment by WXpiero** [comment]
life saver bro， before your post all I can do is disable the app.................
