### ISSUE TITLE
Failing Integrity Check on Admin Overview

### ISSUE THREAD

**Issue by mprtmidcap** [nextcloud/theming_customcss#39]
Love the app by the way, it make life much more pleasant.
Something of note happened after our update to 27.1.6 the other day.  Once the update completed and we checked the Admin Overview page we started to see a failure in the integrity check (details below).  The app works without issue, it just doesn't pass the integrity check.  Wasn't sure if this was the correct place to post or if there was another place I should use.  I searched for existing issues and comments and didn't see anything.  I wanted to let you know of the issue.  If more details are needed please let me know.

The appinfo folder of the app the info.xml and routes.php files and does not include a signature.json file.

From the Admin Overview page:

```
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the [documentation ]. ([List of invalid files…] / [Rescan…]

From the List of invalid files:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- theming_css
	- EXCEPTION
		- Exception
		- App not found
- custom_css
	- EXCEPTION
		- Exception
		- App not found
- custom_themingcss
	- EXCEPTION
		- Exception
		- App not found
- theming_customcss
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [theming_css] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

    [custom_css] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

    [custom_themingcss] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

    [theming_customcss] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )
)
```

**Comment by joshtrichards** [comment]
Hi @mprtmidcap 

The first three references can happen if there are folders in your `apps_paths` that are empty / not valid apps.

As for the main matter: This app isn't a shipped app nor signed on its own (i.e. has no `signature.json`), so the integrity check shouldn't run against it.

I'm unable to reproduce this, even back on v27. You still seeing this?

**Comment by mprtmidcap** [comment]
Hello @joshtrichards,

I have not seen the issue appear again since that particular update.  We are currently on 29.0.5, so it has been several updates ago that we'd seen the issue.

Thank you for checking back with me,
Tony Midcap
